from .cabecalho_section import CabecalhoSection
from .introducao_section import IntroducaoSection
from .identificacao_section import IdentificacaoSection
from .resultados_section import ResultadosSection
from .grafica_section import GraficaSection
from .tomografia_section import TomografiaSection
from .interpretacao_section import InterpretacaoSection
from .conclusao_section import ConclusaoSection